config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users

  resources :friend_requests, only: %i[create update] do
    collection do
      get :pending
      get :accepted
      get :rejected
    end
  end

  resources :users, only: :index
  resources :locations, only: %i[create new]

  get "/timeline", to: "home#timeline"
  get "/:id", to: "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  after_create :send_notification

  belongs_to :user
  belongs_to :friend, class_name: "User"

  scope :received, ->(user) { where(friend_id: user.id) }
  scope :pending,  -> { where(accepted_at: nil, rejected_at: nil) }
  scope :accepted, -> { where.not(accepted_at: nil).where(rejected_at: nil) }
  scope :rejected, -> { where.not(rejected_at: nil).where(accepted_at: nil) }

  def update_request(type)
    if type == "accept"
      update(accepted_at: Time.current)
      friend.update(mutual_friend_ids: friend.mutual_friend_ids.push(user_id))
      user.update(mutual_friend_ids: user.mutual_friend_ids.push(friend_id))
      FriendRequestMailer.request_accepted(id).deliver_now
    elsif type == "reject"
      update(rejected_at: Time.current)
    end
  end

  private

  def send_notification
    FriendRequestMailer.request_received(id).deliver_now
  end
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address

  after_validation :geocode
  before_save :check_valid_address

  belongs_to :user

  has_many :shared_locations, dependent: :destroy
  has_many :users, through: :shared_locations

  validates :address, presence: true

  scope :visible, ->(user_id) { left_outer_joins(:shared_locations).where("locations.user_id = :user_id OR shared_locations.user_id = :user_id", user_id: user_id).distinct }
  scope :publicly_visible, -> { left_outer_joins(:shared_locations).where(shared_locations: { id: nil }) }

  private

  def check_valid_address
    if !latitude && !longitude
      errors.add(:base, "Please enter valid address")
      throw :abort
    end
  end
end

app/models/shared_location.rb
class SharedLocation < ApplicationRecord
  after_create :send_notification

  belongs_to :user
  belongs_to :location

  private

  def send_notification
    LocationSharingMailer.location_shared(id).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :recoverable, :rememberable, :validatable, :confirmable, :lockable

  strip_attributes only: :username, collapse_spaces: true

  has_many :friend_requests,  dependent: :destroy
  has_many :locations,        dependent: :destroy
  has_many :shared_locations, dependent: :destroy

  validates :username, presence: true,
                       length: { maximum: 20 },
                       uniqueness: { case_sensitive: false },
                       format: { with: /\A[a-zA-Z0-9]+\Z/ },
                       exclusion: { in: %w[users home friend_requests locations timeline] }

  validates :email, presence: true, length: { maximum: 100 }

  scope :order_by_username, -> { order(username: :asc) }

  def self.search(query)
    query = query.to_s.strip

    if query.present?
      where("username ILIKE ?", "%#{query}%")
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || timeline_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :authenticate_user!

  def pending
    @friend_requests = FriendRequest.received(current_user).pending.includes(:user)
  end

  def accepted
    @friend_requests = FriendRequest.received(current_user).accepted.includes(:user)
  end

  def rejected
    @friend_requests = FriendRequest.received(current_user).rejected.includes(:user)
  end

  def create
    @friend_request = FriendRequest.create(friend_request_params)
  end

  def update
    @friend_request = FriendRequest.find(params[:id])
    @friend_request.update_request(params[:type])
  end

  private

  def friend_request_params
    params.require(:friend_request).permit(:friend_id).merge(user: current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :timeline

  def index
    redirect_to timeline_path if current_user
  end

  def timeline
    @locations = Location.visible(current_user.id)
    @pagy, @locations = pagy_countless(@locations.includes(:user), items: 21, link_extra: 'data-remote="true"')
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to timeline_path, flash: { success: I18n.t("share_success") }
    else
      render "new"
    end
  end

  private

  def location_params
    params.require(:location).permit(:address, user_ids: []).merge(user: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.search(params[:search]).order_by_username
    @pending_user_ids = FriendRequest.received(current_user).pending.pluck(:user_id)
    @sent_user_ids = current_user.friend_requests.pending.pluck(:friend_id)
  end

  def show
    @user = User.find_by(username: params[:id])

    if @user
      @pagy, @locations = pagy_countless(@user.locations.publicly_visible, items: 21, link_extra: 'data-remote="true"')
    else
      redirect_to timeline_path, flash: { danger: "User is not present with #{params[:id]} username." }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def full_title(page_title = "")
    base_title = t("page_title")

    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def flash_message_prefix(message_type)
    case message_type
    when "success" then t("alert_prefix.success")
    when "info"    then t("alert_prefix.info")
    when "warning" then t("alert_prefix.warning")
    when "danger"  then t("alert_prefix.danger")
    else ""
    end
  end

  def message_type(type)
    case type
    when "notice" then t("message_type.notice")
    when "alert"  then t("message_type.alert")
    else type
    end
  end
end

app/helpers/dropdown_helper.rb
module DropdownHelper
  def friend_list_dropdown
    User.where(id: current_user.mutual_friend_ids).pluck(:username, :id)
  end
end

app/views/friend_requests/accepted.html.erb
<% provide(:title, "Accepted Friend Requests") %>

<section class="header">
  <h4>Accepted Friend Requests</h4>

  <div class="filter-links">
    <%= link_to "Pending", pending_friend_requests_path %>
    <%= link_to "Rejected", rejected_friend_requests_path %>
  </div>
</section>

<% if @friend_requests.blank? %>
  <section class="well">
    No accepted friend requests are present.
  </section>
<% else %>
  <section class="list">
    <% @friend_requests.each do |fr| %>
      <div class="list-item" id="friend_request_<%= fr.id %>">
        <span class="user-name"><%= link_to fr.user.username, "/#{fr.user.username}", title: "Go to #{fr.user.username}" %></span>
      </div>
    <% end %>
  </section>
<% end %>

app/views/friend_requests/create.js.erb
$('#user_<%= @friend_request.friend_id %>').find('.action-buttons').html('<span title="Request Sent">Request Sent</span>');

app/views/friend_requests/pending.html.erb
<% provide(:title, "Pending Friend Requests") %>

<section class="header">
  <h4>Pending Friend Requests</h4>

  <div class="filter-links">
    <%= link_to "Accepted", accepted_friend_requests_path %>
    <%= link_to "Rejected", rejected_friend_requests_path %>
  </div>
</section>

<% if @friend_requests.blank? %>
  <section class="well">
    No pending friend requests are present.
  </section>
<% else %>
  <section class="list">
    <% @friend_requests.each do |fr| %>
      <div class="list-item" id="friend_request_<%= fr.id %>">
        <span class="user-name"><%= link_to fr.user.username, "/#{fr.user.username}", title: "Go to #{fr.user.username}" %></span>

        <div class="action-buttons">
          <%= link_to "Accept", friend_request_path(id: fr.id, type: "accept"), method: :patch, title: "Accept", class: "text-primary mr-2", remote: true %>
          <%= link_to "Reject", friend_request_path(id: fr.id, type: "reject"), method: :patch, title: "Reject", class: "text-danger", remote: true %>
        </div>
      </div>
    <% end %>
  </section>
<% end %>

app/views/friend_requests/rejected.html.erb
<% provide(:title, "Rejected Friend Requests") %>

<section class="header">
  <h4>Rejected Friend Requests</h4>

  <div class="filter-links">
    <%= link_to "Pending", pending_friend_requests_path %>
    <%= link_to "Accepted", accepted_friend_requests_path %>
  </div>
</section>

<% if @friend_requests.blank? %>
  <section class="well">
    No rejected friend requests are present.
  </section>
<% else %>
  <section class="list">
    <% @friend_requests.each do |fr| %>
      <div class="list-item" id="friend_request_<%= fr.id %>">
        <span class="user-name"><%= link_to fr.user.username, "/#{fr.user.username}", title: "Go to #{fr.user.username}" %></span>
      </div>
    <% end %>
  </section>
<% end %>

app/views/friend_requests/update.js.erb
$('#friend_request_<%= @friend_request.id %>').find('.action-buttons').html('<%= params[:type].titleize %>ed');

app/views/home/index.html.erb
<div class="home-container">
  <h2 class="header">Share your location with your frinds and family.</h2>
  <%= image_tag "hero.jpg", alt: "hero image", class: "hero-image" %>
</div>

app/views/home/timeline.html.erb
<% provide(:title, "Timeline") %>

<div class="d-flex justify-content-between mb-5">
  <h4>Timeline</h4>
  <%= link_to "Share Location", new_location_path, remote: true, title: "Share Location", class: "btn btn-primary" %>
</div>

<div class="row" id="locations">
  <%= render "shared/locations" %>

  <% if @locations.blank? %>
    <div class="col-12">
      <div class="jumbotron  text-center">
        <p>No location has been shared yet. <%= link_to "Share now", new_location_path, remote: true, title: "Share Location" %></p>
      </div>
    </div>
  <% end %>
</div>

<div id="auto_next_link">
  <%= render "shared/auto_incremental_pagy" %>
</div>

app/views/home/timeline.js.erb
$('#locations').append("<%= j(render 'shared/locations')%>");
$('#auto_next_link').html("<%= j(render 'shared/auto_incremental_pagy') %>")

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= message_type(type) %> alert-dismissible fade show mb-3" role="alert">
    <strong><%= flash_message_prefix(message_type(type)) %></strong> <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top mb-3 bg-white">
  <div class="container">
    <%= link_to current_user ? timeline_path : root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "logo" %>
    <% end %>

    <span class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <%= image_tag "menu.svg", alt: "menu icon" %>
    </span>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <div class="dropdown">
            <button class="btn btn-link dropdown-toggle nav-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Hi, <%= current_user.username %>
            </button>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "All Users", users_path, class: "dropdown-item" %>
              <%= link_to "Friend Requests", pending_friend_requests_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap">

    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://openlayers.org/en/v4.6.5/css/ol.css" type="text/css">

    <script src="https://openlayers.org/en/v4.6.5/build/ol.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container" id="main_content">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>

    <%= render "locations/location_modal" %>
  </body>
</html>

app/views/locations/_form.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="formModal">Share your Location</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= form_for @location, remote: true do |f| %>
  <div class="modal-body">
    <%= render "shared/error_messages", resource: @location %>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control", placeholder: "Address", required: true %>
    </div>

    <div class="form-group">
      <%= label_tag "location[user_ids][]", "Select Friend" %>
      <%= select_tag "location[user_ids][]", options_for_select(friend_list_dropdown), class: "form-control", multiple: true, placeholder: "Users" %>
    </div>
    <small class="text-muted">If you are not selecting any user, then location will be publicly visible.</small>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" title="Close">Close</button>
    <%= f.submit "Share", class: "btn btn-primary", disabled_with: "Saving..." , title: "Share Location" %>
  <div>
<% end %>

app/views/locations/_location_modal.html.erb
<div class="modal fade" id="location_modal" tabindex="-1" role="dialog" aria-labelledby="formModal" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/locations/new.js.erb
$('#location_modal').find('.modal-content').html('<%= j (render "form") %>');
$('#location_modal').modal();

app/views/shared/_auto_incremental_pagy.html.erb
<%== pagy_next_link(@pagy, '', 'id="next_link" class="d-none"') %>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger">
    <% resource.errors.full_messages.each.with_index(1) do |msg, index| %>
      <p class="mb-0"><%= index %>. <%= msg %>.</p>
    <% end %>
  </div>
<% end %>

app/views/shared/_location.html.erb
<div id="map_<%= object.id %>" class="map"></div>

<script>
  var baseMapLayer = new ol.layer.Tile({
    source: new ol.source.OSM()
  });
  var map = new ol.Map({
    target: 'map_<%= object.id %>',
    layers: [ baseMapLayer],
    view: new ol.View({
            center: ol.proj.fromLonLat([<%= object.longitude %>, <%= object.latitude %>]),
            zoom: 7 //Initial Zoom Level
          })
  });

  var marker = new ol.Feature({
    geometry: new ol.geom.Point(
      ol.proj.fromLonLat([<%= object.longitude %>, <%= object.latitude %>])
    ),
  });

  var vectorSource = new ol.source.Vector({
    features: [marker]
  });
  var markerVectorLayer = new ol.layer.Vector({
    source: vectorSource,
  });
  map.addLayer(markerVectorLayer);
</script>

app/views/shared/_locations.html.erb
<% @locations.reverse.each do |location| %>
  <div class="col-sm-12 col-lg-6 col-xl-4">
    <div class="card p-3 mb-4">
      <h6><%= location.address %></h6>
      <small class="text-muted mb-2">Shared by <%= location.user == current_user ? "you" : "<a href='/#{location.user.username}'>#{location.user.username}</a>".html_safe %></small>
      <%= render "shared/location", object: location %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>

<section class="header">
  <h4>All Users</h4>
</section>

<%= form_tag users_path, method: :get  do %>
  <%= search_field_tag :search, params[:search], class: "form-control", placeholder: "Search by username" %>
  <small class="text-muted">Press ↵ enter to search</small>
<% end %>

<% if @users.blank? %>
  <section class="well">
    No user present
  </section>
<% else %>
  <section class="list">
    <% @users.each do |user| %>
      <div class="list-item" id="user_<%= user.id %>">
        <span class="user-name"><%= link_to user.username, "/#{user.username}", title: "Go to #{user.username}" %></span>

        <% if user != current_user %>
          <div class="action-buttons">
            <% if current_user.mutual_friend_ids.include?(user.id.to_s) %>
              <span title="Already Friend">Already Friend</span>
            <% elsif @pending_user_ids.include?(user.id) %>
              <span title="Request Received">Request Received</span>
            <% elsif @sent_user_ids.include?(user.id) %>
              <span title="Request Sent">Request Sent</span>
            <% else %>
              <%= link_to "Send Request", friend_requests_path(friend_request: { friend_id: user.id }), method: :post, title: "Send Request", class: "text-primary", remote: true %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </section>
<% end %>

app/views/users/shared/_links.html.erb
<% if controller_name != "sessions" %>
  <p class="mb-1">Do you have an account? <%= link_to "Login", new_session_path(resource_name) %></p>
<% end %>

<% if devise_mapping.registerable? && controller_name != "registrations" %>
  <p class="mb-1">Don't you have an account? <%= link_to "Signup", new_registration_path(resource_name) %></p>
<% end %>

<% if devise_mapping.confirmable? && controller_name != "confirmations" %>
  <p class="mb-1">Didn't receive confirmation email? <%= link_to "Click here", new_confirmation_path(resource_name) %></p>
<% end %>

<% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks" %>
  <p class="mb-1">Didn't receive unlock email? <%= link_to "Click here", new_unlock_path(resource_name) %></p>
<% end %>

<% if devise_mapping.omniauthable? %>
  <hr>

  <% resource_class.omniauth_providers.each do |provider| %>
    <p class="mb-1">Sign in with <%= link_to "#{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %></p>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "#{@user.username}'s timeline") %>

<h4 class="mb-5"><%= @user.username %>'s timeline</h4>

<div class="row" id="locations">
  <%= render "shared/locations" %>

  <% if @locations.blank? %>
    <div class="col-12">
      <div class="jumbotron text-center">
        <p>No location has been shared by <%= @user.username %>.</p>
      </div>
    </div>
  <% end %>
</div>

<div id="auto_next_link">
  <%= render "shared/auto_incremental_pagy" %>
</div>

app/views/users/show.js.erb
$('#locations').append("<%= j(render 'shared/locations')%>");
$('#auto_next_link').html("<%= j(render 'shared/auto_incremental_pagy') %>")